fishing:
  x: 1575
  y: 500
  width: 300
  height: 500
  timeouts:
    loop:
      min: 0
      max: 100
    notice:
      min: 1.5
      max: 2.0
    reeling:
      min: 0.4
      max: 0.9
    pause:
      min: 0
      max: 0.1
    cast:
      min: 0.1
      max: 0.3
repairing:
  x: 1600
  y: 875
  length: 25
  every: 400
  enable: 1
  timeouts:
    arm_disarm:
      min: 1
      max: 1.5
    inventory:
      min: 1
      max: 1.5
    repair:
      min: 1
      max: 1.5
    confirm:
      min: 1
      max: 1.5
    move_around:
      min: 0.5
      max: 1.0
bait:
  bait_x: 2000
  bait_y: 600
  equip_button_x: 2400
  equip_button_y: 1100
  length: 25
  enable: 1
  timeouts:
    select:
      min: 0.1
      max: 1
    confirm:
      min: 0.1
      max: 1
colors:
  green:
    r: 4
    g: 227
    b: 162
  brown:
    r: 230
    g: 110
    b: 22
  red:
    r: 109
    g: 18
    b: 21
resolution:
  x: 5120
  y: 2160
log_lvl: DEBUG
